CREATE TABLE `MEMBER` (
	`MEM_NO`	NUMBER	NOT NULL	COMMENT '회원번호',
	`MEM_ID`	VARCHAR(30)	NOT NULL	COMMENT '회원아이디',
	`MEM_PW`	VARCHAR(30)	NOT NULL	COMMENT '비밀번호',
	`MEM_NAME`	VARCHAR(20)	NOT NULL	COMMENT '회원명',
	`HIRE_DATE`	DATE	NULL	DEFAULT SYSDATE	COMMENT '회원가입일',
	`ADDRESS`	VARCHAR(255)	NULL	COMMENT '주소',
	`PHONE`	VARCHAR2(20)	NULL	COMMENT '전화번호'
);

CREATE TABLE `PRODUCT` (
	`PNO`	NUMBER	NOT NULL	COMMENT '상품번호',
	`PNAME`	VARCHAR2(30)	NOT NULL	COMMENT '상품명',
	`PDETAIL`	VARCHAR2(50)	NULL	COMMENT '상세정보',
	`CATEGORY`	VARCHAR2(30)	NOT NULL	COMMENT '카테고리',
	`PRCIE`	NUMBER	NOT NULL	COMMENT '가격',
	`STOCK`	NUMBER	NOT NULL	COMMENT '재고수량'
);

CREATE TABLE `REVIEW` (
	`RE_NO`	NUMBER	NOT NULL	COMMENT '리뷰번호',
	`RATING`	NUMBER	NULL	COMMENT '평점',
	`RE_DATE`	DATE	NULL	DEFAULT SYSDATE	COMMENT '작성일',
	`MEM_NO`	NUMBER	NOT NULL	COMMENT '회원번호',
	`PNO`	NUMBER	NOT NULL	COMMENT '상품번호'
);

CREATE TABLE `FAVORITES` (
	`PNO`	NUMBER	NOT NULL	COMMENT '상품번호',
	`MEM_NO`	NUMBER	NOT NULL	COMMENT '회원번호',
	`FDATE`	VARCHAR(255)	NULL	COMMENT '찜한날짜'
);

ALTER TABLE `MEMBER` ADD CONSTRAINT `PK_MEMBER` PRIMARY KEY (
	`MEM_NO`
);

ALTER TABLE `PRODUCT` ADD CONSTRAINT `PK_PRODUCT` PRIMARY KEY (
	`PNO`
);

ALTER TABLE `REVIEW` ADD CONSTRAINT `PK_REVIEW` PRIMARY KEY (
	`RE_NO`
);

ALTER TABLE `FAVORITES` ADD CONSTRAINT `PK_FAVORITES` PRIMARY KEY (
	`PNO`,
	`MEM_NO`
);

ALTER TABLE `FAVORITES` ADD CONSTRAINT `FK_PRODUCT_TO_FAVORITES_1` FOREIGN KEY (
	`PNO`
)
REFERENCES `PRODUCT` (
	`PNO`
);

ALTER TABLE `FAVORITES` ADD CONSTRAINT `FK_MEMBER_TO_FAVORITES_1` FOREIGN KEY (
	`MEM_NO`
)
REFERENCES `MEMBER` (
	`MEM_NO`
);

